print("hello")
name = input("enter your name:")
num1 = float(input("enter your first number:"))
num2 = float(input("enter your second number"))
sum_result = (num1 + num2)
subtraction_result = (num1 - num2)
multiplication_result = (num1 * num2)
division_result = (num1 / num2)
print("the sum is",sum_result)
print("the subtraction result is",subtraction_result)
print("the multiplication result is",multiplication_result)
print("the division result is",division_result)
